### ISSUE TITLE
'str' object has no attribute 'get' on 2.0.27

### ISSUE THREAD

**Issue by phenobarbital** [O365/python-o365#979]
I'm facing the same problem seeing on this discussion: https://github.com/O365/python-o365/discussions/973

The error happens on "send()" method of Message, in line 796 of _internal_request, "error" is expecting to be a dictionary but is an string:

``
Traceback (most recent call last):
  File "/home/jesuslara/proyectos/navigator/notify/notify/providers/office365/office365.py", line 185, in _send_
    message.send()
  File "/home/jesuslara/proyectos/navigator/notify/.venv/lib/python3.10/site-packages/O365/message.py", line 720, in send
    response = self.con.post(url, data=data)
  File "/home/jesuslara/proyectos/navigator/notify/.venv/lib/python3.10/site-packages/O365/connection.py", line 876, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "/home/jesuslara/proyectos/navigator/notify/.venv/lib/python3.10/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/jesuslara/proyectos/navigator/notify/.venv/lib/python3.10/site-packages/O365/connection.py", line 796, in _internal_request
    error.get("error", {}).get("innerError", "").get("code", "")
AttributeError: 'str' object has no attribute 'get'
``

I'm using the last version of O365 (2.0.27) because I'm using the default scope Outlook ("https://outlook.office.com/.default") but in the previous version (2.0.26) is working and returning the exact error for "send()":

``
403 Client Error:  for url: https://outlook.office.com/api/v2.0/me/sendMail | Error Message: Access is denied. Check credentials and try again
``

My connection code looks like:
``
            self.account = Account(
                credentials=credentials,
                auth_flow_type="credentials",
                tenant_id=self.tenant_id,
                protocol=MSOffice365Protocol(**kwargs),
                token_backend=FileSystemTokenBackend(
                   token_path='.',
                   token_filename='.o365_token.txt'
                 )
            )
``

Authentication is successful and also the token_filename exists, if I fix the "Access Denied" on the Office 365 account, then method "send()" works on both versions (2.0.26 and .27).

**Comment by janscas** [comment]
I'll investigate this line of code.

> line 796, in _internal_request error.get("error", {}).get("innerError", "").get("code", "") AttributeError: 'str' object has no attribute 'get'


Thanks

**Comment by rasshe** [comment]
I think the line should be changed from 
`error.get("error", {}).get("innerError","").get("code", "")`
To
`error.get("error", {}).get("innerError",{}).get("code", "")`

If the innerError is not found it returns a string which does not have `get` method
